/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutDemoRouteImport } from './routes/_layout/demo'
import { Route as LayoutCheckoutRouteImport } from './routes/_layout/checkout'
import { Route as LayoutSettingsAddressesRouteImport } from './routes/_layout/settings/addresses'
import { Route as LayoutListingIdRouteImport } from './routes/_layout/listing/$id'

const LayoutIndexLazyRouteImport = createFileRoute('/_layout/')()

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexLazyRoute = LayoutIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoRoute = LayoutDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutRoute = LayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsAddressesRoute = LayoutSettingsAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutListingIdRoute = LayoutListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/demo': typeof LayoutDemoRoute
  '/products': typeof LayoutProductsRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof LayoutIndexLazyRoute
  '/listing/$id': typeof LayoutListingIdRoute
  '/settings/addresses': typeof LayoutSettingsAddressesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/demo': typeof LayoutDemoRoute
  '/products': typeof LayoutProductsRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof LayoutIndexLazyRoute
  '/listing/$id': typeof LayoutListingIdRoute
  '/settings/addresses': typeof LayoutSettingsAddressesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/demo': typeof LayoutDemoRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_layout/': typeof LayoutIndexLazyRoute
  '/_layout/listing/$id': typeof LayoutListingIdRoute
  '/_layout/settings/addresses': typeof LayoutSettingsAddressesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/chat'
    | '/checkout'
    | '/demo'
    | '/products'
    | '/settings'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/'
    | '/listing/$id'
    | '/settings/addresses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/chat'
    | '/checkout'
    | '/demo'
    | '/products'
    | '/settings'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/'
    | '/listing/$id'
    | '/settings/addresses'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/chat'
    | '/_layout/checkout'
    | '/_layout/demo'
    | '/_layout/products'
    | '/_layout/settings'
    | '/auth/sign-in'
    | '/auth/verify'
    | '/_layout/'
    | '/_layout/listing/$id'
    | '/_layout/settings/addresses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo': {
      id: '/_layout/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof LayoutDemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/addresses': {
      id: '/_layout/settings/addresses'
      path: '/addresses'
      fullPath: '/settings/addresses'
      preLoaderRoute: typeof LayoutSettingsAddressesRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/listing/$id': {
      id: '/_layout/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof LayoutListingIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutSettingsRouteChildren {
  LayoutSettingsAddressesRoute: typeof LayoutSettingsAddressesRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsAddressesRoute: LayoutSettingsAddressesRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutDemoRoute: typeof LayoutDemoRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutIndexLazyRoute: typeof LayoutIndexLazyRoute
  LayoutListingIdRoute: typeof LayoutListingIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutDemoRoute: LayoutDemoRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutIndexLazyRoute: LayoutIndexLazyRoute,
  LayoutListingIdRoute: LayoutListingIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
